# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""A minimal, Python-only Dynamic Gradient Descent (DGD) Search Strategy.

This strategy reuses existing MetaSchedule components (TuneContext, Database, CostModel,
Builder/Runner) and explores a local neighborhood around a measured base trace by modifying
SamplePerfectTile decisions. It follows a lean adaptation of the algorithmic flow used by
auto_scheduler's DGD reference:

- Extract a compact coordinate vector from a trace (only SamplePerfectTile decisions).
- Generate +/- 1 hop neighbors (1-hop, then 2-hop) in this coordinate space, with product
  preservation via recomputing the last tile factor.
- Use cost model to score and filter; measure small sliding windows; migrate base if better.

Notes:
- To keep the implementation minimal and non-intrusive, we only operate on SamplePerfectTile
  decisions and ignore other stochastic choices (e.g., SampleCategorical). This is sufficient
  for many common spaces generated by PostOrderApply.
- No C++ changes. All logic is implemented in Python, as a PySearchStrategy.
"""
from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations, product
from math import isqrt, prod
import time
from typing import List, Optional, Tuple, Dict, Any

from tvm.tir.schedule import Schedule, Trace
from tvm.tir.schedule.instruction import Instruction

from ..arg_info import ArgInfo
from ..database import Database, TuningRecord, Workload
from ..runner import RunnerResult
from ..search_strategy import MeasureCandidate, PySearchStrategy
from ..tune_context import TuneContext
from ..utils import derived_object, shash2hex


def _factors(n: int) -> List[int]:
    """Return sorted factors of n (>=1)."""
    if n <= 0:
        return [1]
    res = []
    r = isqrt(n)
    for i in range(1, r + 1):
        if n % i == 0:
            res.append(i)
            j = n // i
            if j != i:
                res.append(j)
    res.sort()
    return res


@dataclass
class _TileSite:
    inst: Instruction
    # original full decision for the SamplePerfectTile, e.g. [a, b, c, d]
    decision: List[int]
    # how many editable coordinates we expose (we keep last factor derived)
    length_exposed: int


class _TraceCoordinateCodec:
    """Encode/decode SamplePerfectTile decisions into/from a flat coordinate list.

    We expose all but the last factor for each SamplePerfectTile decision as editable
    coordinates. When applying new coordinates, the last factor is recomputed to preserve
    the original product.
    """

    def __init__(self, trace: Trace) -> None:
        self.trace = trace
        self.sites: List[_TileSite] = []

    def extract(self) -> List[int]:
        coords: List[int] = []
        # Note: decisions are stored in trace.decisions; use get_decision for safety
        for inst in self.trace.insts:
            if inst.kind.name == "SamplePerfectTile":
                dec = self.trace.get_decision(inst)
                if dec is None:
                    # If the decision is not available, skip this site
                    continue
                dec_list: List[int] = []
                for x in dec:
                    # x can be IntImm; convert to python int via .value if present
                    try:
                        dec_list.append(int(getattr(x, "value", x)))
                    except Exception:  # pylint: disable=broad-except
                        dec_list.append(int(x))
                if len(dec_list) >= 2:
                    # Expose l-1 dims; keep last derived on apply
                    self.sites.append(_TileSite(inst=inst, decision=dec_list, length_exposed=len(dec_list) - 1))
                    coords.extend(dec_list[:-1])
        return coords

    def apply(self, base_mod, new_coords: List[int]) -> Optional[Schedule]:
        # Create a fresh schedule and apply a mutated trace with updated tile decisions
        try:
            sch = Schedule(base_mod)
        except Exception:  # pylint: disable=broad-except
            return None

        coord_idx = 0
        new_trace: Trace = self.trace
        for site in self.sites:
            exposed = new_coords[coord_idx : coord_idx + site.length_exposed]
            coord_idx += site.length_exposed
            # reconstruct last factor by preserving product
            original_prod = prod(site.decision)
            new_prefix_prod = prod(exposed) if len(exposed) > 0 else 1
            if new_prefix_prod <= 0 or original_prod % new_prefix_prod != 0:
                return None
            last = original_prod // new_prefix_prod
            if last <= 0:
                return None
            new_decision = list(exposed) + [int(last)]
            # Replace decision for this instruction, remove postproc when rewriting
            try:
                new_trace = new_trace.with_decision(site.inst, new_decision, remove_postproc=True)
            except Exception:  # pylint: disable=broad-except
                return None

        try:
            # Apply the mutated trace
            new_trace.apply_to_schedule(sch, remove_postproc=True)
        except Exception:  # pylint: disable=broad-except
            return None
        return sch


def _gen_neighbors(coords: List[int], sites: List[_TileSite], n_hop: int) -> List[List[int]]:
    """Generate +/-1 hop neighbor coordinate vectors.

    For each exposed coordinate, define its admissible factor list from the product of
    the corresponding SamplePerfectTile site. Then move index by +/-1 when possible.
    """
    if not coords:
        return []
    # Build per-dimension factor lists
    per_dim_factors: List[List[int]] = []
    for site in sites:
        # only for exposed dims
        original_prod = prod(site.decision)
        factors = _factors(original_prod)
        for _ in range(site.length_exposed):
            per_dim_factors.append(factors)

    neighbors: List[List[int]] = []
    dim = len(coords)
    base = coords
    # Enumerate index subsets of size n_hop
    for idxs in combinations(range(dim), n_hop):
        for delta in product([-1, 1], repeat=n_hop):
            cand = list(base)
            valid = True
            for i, d in zip(idxs, delta):
                f_list = per_dim_factors[i]
                cur = base[i]
                # map current value to its index in factor list (fallback random if not present)
                try:
                    cur_pos = f_list.index(cur)
                except ValueError:
                    # if value not in factors, snap to nearest factor
                    # choose the closest factor by value
                    diffs = [abs(x - cur) for x in f_list]
                    cur_pos = int(diffs.index(min(diffs)))
                new_pos = cur_pos + d
                if new_pos < 0 or new_pos >= len(f_list):
                    valid = False
                    break
                cand[i] = f_list[new_pos]
            if valid and cand != base:
                neighbors.append(cand)
    return neighbors


@derived_object
class DGDMinimal(PySearchStrategy):
    """Minimal Dynamic Gradient Descent search strategy (pure Python).

    Parameters
    ----------
    n_start : int
        Number of initial base points picked from measured samples.
    init_size : int
        Number of warm-up samples to build initial model.
    slide_window_size : int
        Number of candidates to measure per step.
    max_trials : int
        Global measurement budget (per task).
    max_tuning_time_s : int
        Global wall-time budget in seconds (per task).
    predict_score_ratio : float
        Predict score threshold ratio relative to base (keep >= base_score * ratio).
    measure_threshold_ratio : float
        Early stop threshold for measured throughput relative to best seen.
    shared_mem_view : bool
        Placeholder for CUDA constraints (not enforced in minimal version).
    """

    def __init__(
        self,
        *,
        n_start: int = 5,
        init_size: int = 64,
        slide_window_size: int = 3,
        max_trials: int = 1000,
        max_tuning_time_s: int = 120,
        predict_score_ratio: float = 0.6,
        measure_threshold_ratio: float = 0.6,
        shared_mem_view: bool = True,
    ) -> None:
        super().__init__()
        # hyper-params
        self.n_start = n_start
        self.init_size = init_size
        self.slide_window_size = slide_window_size
        self.max_trials = max_trials
        self.max_tuning_time_s = max_tuning_time_s
        self.predict_score_ratio = predict_score_ratio
        self.measure_threshold_ratio = measure_threshold_ratio
        self.shared_mem_view = shared_mem_view
        # runtime states
        self.ctx: Optional[TuneContext] = None
        self.database: Optional[Database] = None
        self.cost_model = None
        self.design_spaces: List[Schedule] = []
        self.workload: Optional[Workload] = None
        self.target = None
        self.args_info: Optional[List[ArgInfo]] = None
        self.num_trials_per_iter: int = 64
        self.measured_cnt: int = 0
        self.start_time: float = 0.0
        self._warmup_left: int = 0
        self._pending_init_spaces: List[Schedule] = []
        self._finished: bool = False
        # base and neighborhood queue
        self._current_base: Optional[TuningRecord] = None
        self._neighbor_coords: List[List[int]] = []
        self._neighbor_idx: int = 0
        self._visited_hash: set[str] = set()
        self._best_throughput: float = 0.0

    # API methods
    def _initialize_with_tune_context(self, context: TuneContext) -> None:  # type: ignore
        self.ctx = context
        self.target = context.target
        self.start_time = time.time()

    def pre_tuning(
        self,
        max_trials: int,
        num_trials_per_iter: int,
        design_spaces: List[Schedule],
        database: Optional[Database] = None,
        cost_model=None,
    ) -> None:
        self.max_trials = max_trials
        self.num_trials_per_iter = num_trials_per_iter
        self.design_spaces = design_spaces
        self.database = database
        self.cost_model = cost_model
        assert self.ctx is not None
        self.workload = self.database.commit_workload(self.ctx.mod)
        # args_info derived from entry function once
        self.args_info = ArgInfo.from_entry_func(self.ctx.mod, remove_preproc=True)
        # warmup queue: simply push available design_spaces copies up to init_size
        self._pending_init_spaces = list(self.design_spaces)
        self._warmup_left = max(0, self.init_size)

    def post_tuning(self) -> None:
        self._finished = True

    def _time_budget_exceeded(self) -> bool:
        return (time.time() - self.start_time) >= float(self.max_tuning_time_s)

    def _trial_budget_exceeded(self) -> bool:
        return self.measured_cnt >= self.max_trials

    def _gen_candidates_from_spaces(self, spaces: List[Schedule], limit: int) -> List[MeasureCandidate]:
        cands: List[MeasureCandidate] = []
        for sch in spaces[:limit]:
            cands.append(MeasureCandidate(sch, self.args_info))
        return cands

    def _pick_bases_from_db(self) -> Optional[TuningRecord]:
        # prefer best from db
        assert self.database is not None and self.workload is not None
        topk_arr = self.database.get_top_k(self.workload, max(self.n_start, 1))
        if len(topk_arr) == 0:
            return None
        topk = list(topk_arr)
        # each record.run_secs is a list of floats; select the minimal average
        def avg_cost(rec: TuningRecord) -> float:
            rs = rec.run_secs or []
            return float(sum(rs) / len(rs)) if rs else 1e9

        topk.sort(key=avg_cost)
        return topk[0]

    def _build_neighbors_for_base(self, base: TuningRecord) -> None:
        # extract coordinates from base trace
        codec = _TraceCoordinateCodec(base.trace)
        coords = codec.extract()
        self._neighbor_coords = []
        self._neighbor_idx = 0
        if not coords:
            return
        # generate 1-hop and 2-hop neighbors
        nh1 = _gen_neighbors(coords, codec.sites, 1)
        nh2 = _gen_neighbors(coords, codec.sites, 2)
        all_neighbors = nh1 + nh2
        # convert to measure candidates with scoring
        candidates: List[Tuple[float, MeasureCandidate]] = []
        base_score: float = 1.0
        # base decision score via its own schedule
        base_cand = base.as_measure_candidate()
        base_score = float(self.cost_model.predict(self.ctx, [base_cand])[0])

        # apply, deduplicate, score
        for nc in all_neighbors:
            sch = codec.apply(base.workload.mod, nc)
            if sch is None:
                continue
            key = shash2hex(sch.mod)
            if key in self._visited_hash:
                continue
            cand = MeasureCandidate(sch, self.args_info)
            score = float(self.cost_model.predict(self.ctx, [cand])[0])
            if score >= base_score * self.predict_score_ratio:
                candidates.append((score, cand))
        # sort by score desc
        candidates.sort(key=lambda x: -x[0])
        # keep order only of candidates
        self._neighbors_scored = [c for _, c in candidates]

    def generate_measure_candidates(self) -> Optional[List[MeasureCandidate]]:
        if self._finished or self._trial_budget_exceeded() or self._time_budget_exceeded():
            return None
        # warmup stage
        if self._warmup_left > 0 and self._pending_init_spaces:
            take = min(self._warmup_left, self.num_trials_per_iter)
            spaces = self._pending_init_spaces[:take]
            self._pending_init_spaces = self._pending_init_spaces[take:]
            cands = self._gen_candidates_from_spaces(spaces, take)
            return cands if cands else None

        # ensure a base is set
        if self._current_base is None:
            base = self._pick_bases_from_db()
            if base is None:
                # no measured data yet; try to emit remaining spaces (if any)
                if self._pending_init_spaces:
                    take = min(self.num_trials_per_iter, len(self._pending_init_spaces))
                    spaces = self._pending_init_spaces[:take]
                    self._pending_init_spaces = self._pending_init_spaces[take:]
                    return self._gen_candidates_from_spaces(spaces, take)
                return None
            self._current_base = base
            # prepare neighbor list for this base
            self._build_neighbors_for_base(self._current_base)

        # emit a sliding window batch from neighbors
        window: List[MeasureCandidate] = []
        take = self.slide_window_size
        while len(window) < take and self._neighbor_idx < len(self._neighbors_scored):
            cand = self._neighbors_scored[self._neighbor_idx]
            self._neighbor_idx += 1
            key = shash2hex(cand.sch.mod)
            if key in self._visited_hash:
                continue
            window.append(cand)
        if not window:
            # exhausted neighbors; reset base to None to pick another on next iter
            self._current_base = None
            if not self._trial_budget_exceeded() and not self._time_budget_exceeded():
                return self.generate_measure_candidates()
            return None
        return window

    def notify_runner_results(
        self,
        measure_candidates: List[MeasureCandidate],
        results: List[RunnerResult],
    ) -> None:
        # Commit records and update states / model
        assert self.database is not None and self.workload is not None and self.ctx is not None
        # Update best throughput tracker and visited set
        batch_costs: List[float] = []
        for cand, res in zip(measure_candidates, results):
            # Create and commit a tuning record
            run_secs = [float(x.value) for x in (res.run_secs or [])] if res.run_secs else []
            tr = TuningRecord(
                trace=cand.sch.trace.simplified(remove_postproc=True),
                workload=self.workload,
                run_secs=run_secs,
                target=self.target,
                args_info=cand.args_info,
            )
            self.database.commit_tuning_record(tr)

            # book-keeping
            self._visited_hash.add(shash2hex(cand.sch.mod))
            if run_secs:
                cost = float(sum(run_secs) / len(run_secs))
            else:
                cost = 1e9
            batch_costs.append(cost)
            if cost > 0:
                self._best_throughput = max(self._best_throughput, 1.0 / cost)

        # Count trials
        self.measured_cnt += len(measure_candidates)

        # Early stop condition on measured performance
        if batch_costs:
            cur_best = min(batch_costs)
            if self._best_throughput > 0:
                if 1.0 / cur_best < self._best_throughput * self.measure_threshold_ratio:
                    # current window underperforms; exhaust window by skipping remaining
                    self._neighbor_idx = len(getattr(self, "_neighbors_scored", []))

        # If current batch discovers a better-than-base point, migrate base
        if self._current_base is not None and batch_costs:
            base_cost = float(sum(self._current_base.run_secs or [1e9]) / max(1, len(self._current_base.run_secs or [])))
            win_best = min(batch_costs)
            if win_best + 1e-12 < base_cost:
                # pick the corresponding record in DB as new base (query best again)
                self._current_base = self._pick_bases_from_db()
                if self._current_base is not None:
                    self._build_neighbors_for_base(self._current_base)
        # Warmup decrement
        if self._warmup_left > 0:
            self._warmup_left = max(0, self._warmup_left - len(measure_candidates))

        # Stop flag
        if self._trial_budget_exceeded() or self._time_budget_exceeded():
            self._finished = True

        # Let cost model update online as well (in case measure callback not used)
        try:
            self.cost_model.update(self.ctx, measure_candidates, results)
        except Exception:  # pylint: disable=broad-except
            pass

    def clone(self):  # type: ignore
        return DGDMinimal(
            n_start=self.n_start,
            init_size=self.init_size,
            slide_window_size=self.slide_window_size,
            max_trials=self.max_trials,
            max_tuning_time_s=self.max_tuning_time_s,
            predict_score_ratio=self.predict_score_ratio,
            measure_threshold_ratio=self.measure_threshold_ratio,
            shared_mem_view=self.shared_mem_view,
        )



